#AKMS
apiVersion: kind.x-k8.io/v1alpha4
kind: Pod
metadeta:
  name: twsCluster
spec:
- conteners: control-plane
  image: kindest/node:v1.32.0
- conteners: worker
  image: kindest/node:v1.32.0
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
- conteners: worker
  image: kindest/node:v1.32.0
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
- conteners: worker
  image: kindest/node:v1.32.0
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP

